### ISSUE TITLE
Data setup: WMT preprocessing in data_setup.py

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#104]
There are currently has to be downloaded manually and there does not exist any documentation with instructions.

## Description

The WMT workload requires the wmt17_translate/de-en and wmt14_translate/de-en datasets which have to be downloaded manually with tfds.load. During the download the user may run into issues, for example when downloading wmt14_translate/de-en I ran into ResourceExhausted errors during the generating step. The solution was to manually increase the open file limit on the system as described [here](https://github.com/tensorflow/datasets/issues/1441).

## Steps to Reproduce
VM: tf-agents/in-to-win
In python terminal run `tfds.load('wmt14_translate/de-en')

## Source or Possible Fix
We should either:
- Document instructions to download the datasets for WMT workload clearly, including workarounds for anticipated issues.
- Automate the downloading of the data, perhaps as a prerequisite step.

**Comment by priyakasimbeg** [comment]
From email thread with @runame it seems like the recommended instructions for downloading this dataset are in the [flax examples repo](https://github.com/google/flax/tree/main/examples/wmt).

**Comment by runame** [comment]
@priyakasimbeg I think this issue was addressed in #235?

**Comment by runame** [comment]
Fixed by #444.
