### ISSUE TITLE
Add instructions for downloading and pre-processing data for each workload

### ISSUE THREAD

**Issue by fsschneider** [mlcommons/algorithmic-efficiency#107]
## Description

Each workload should have a readme with clear instructions on how (and precisely which) data should be downloaded and pre-processed.
Ideally, this should come in the form of a script, so it can be automated.

See also #104

**Comment by runame** [comment]
@priyakasimbeg Should we close this, remaining issues with the data setup should probably be more specific?

**Comment by priyakasimbeg** [comment]
Finishing up editing datasets/README instructions and testing the setup commands. Sent out https://github.com/mlcommons/algorithmic-efficiency/pull/510. So I think we can close this.
