### ISSUE TITLE
Finish train_{mean,stddev}

### ISSUE THREAD

**Issue by znado** [mlcommons/algorithmic-efficiency#159]
Right now we have only a few train_{mean,stddev} functions implemented. It should be possible for at least FastMRI and LibriSpeech to compute these statistics once offline and add them to the code. For other workloads that have categorical features (OGBG, WMT, Criteo), we should probably raise a NotImplementedError and the user can catch it. For Criteo it is a bit more open ended, because some of the features are continuous, so we could return those and -1 for the rest, but I think that may be confusing to the user.

**Comment by pomonam** [comment]
Closing this as it was resolved in #332. Note that we raise `NotImplementedError` for workloads that do not make sense to have `train_{mean,stddev}`.
