### ISSUE TITLE
Deduplicate Librispeech code

### ISSUE THREAD

**Issue by znado** [mlcommons/algorithmic-efficiency#162]
Right now the two Librispeech Jax workloads have some duplicate components, we should have deepspeech import the conformer versions.

We should also clearly document in the data pipeline and in multiple places in the workload that the paddings are inverted so that submitters are less confused.

**Comment by priyakasimbeg** [comment]
I refactored part of the Deepspeech code to fix a bug where Deepspeech where Deepspeech was unintentionally inheriting some Conformer workload properties. Won't fix any further.
