### ISSUE TITLE
is_output_params defined as pass or NotImplementedError

### ISSUE THREAD

**Issue by pomonam** [mlcommons/algorithmic-efficiency#165]
In all workloads, `is_output_params` is set to either `pass` or `NotImplementedError`, i.e.
```
  # Return whether or not a key in spec.ParameterTree is the output layer
  # parameters.
  def is_output_params(self, param_key: spec.ParameterKey) -> bool:
    raise NotImplementedError
```
What is the correct implementation? I am assuming we need to provide a model-framework-specific key?

**Comment by znado** [comment]
Yep we need to implement the definition in each workload, we should return if the key matches whatever the model has as the final layer

**Comment by pomonam** [comment]
Sounds good. I have already implemented this. Once we get all PRs merged, I will make another PR that implements this :)
