### ISSUE TITLE
Make target evaluation metric more accessible

### ISSUE THREAD

**Issue by fsschneider** [mlcommons/algorithmic-efficiency#18]
Currently, the target value to achieve in each workload is only defined via the `has_reached_goal` function, i.e.

https://github.com/mlcommons/algorithmic-efficiency/blob/584769427aceeac2835c055fae40f159d4a415d7/workloads/mnist/workload.py#L6-L7

As discussed in the rules draft, submissions should have access to the target value, i.e. to adapt the behavior in the self-tuning ruleset once close to this finish line. I believe we could make this value more accessible by directly providing it as a property of the workload. Perhaps like this:

```python
class Mnist(spec.Workload):

  def has_reached_goal(self, eval_result: float) -> bool:
    return eval_result['accuracy'] > self.target_value

  @property
  def target_value(self):
    return 0.9
```

@znado @hanlint

**Comment by hanlint** [comment]
👍
