### ISSUE TITLE
Check initializations for JAX and PyTorch are the same.

### ISSUE THREAD

**Issue by pomonam** [mlcommons/algorithmic-efficiency#189]
We need to make sure the initialization methods for JAX and PyTorch are the same. 

Moreover, making a unit test to check the outputs are almost the same when the model params are the same for JAX and PyTorch and we are using the same mini-batch. We may need to hard-code the correspondence between Jax `param_key` and PyTorch `param_key`, but it would be useful as it shows that the same operations are being performed.

**Comment by chandramouli-sastry** [comment]
i'll work on testing the conformer model!

**Comment by pomonam** [comment]
Note that the initialization schemes are now all unified except for librispeech workloads.

**Comment by pomonam** [comment]
Closing with #195.
