### ISSUE TITLE
resuming experiment default behavior

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#215]
Imagenet pytorch workload is returning an error when loading the model state_dict.

## Description
Traceback:
 File "/home/kasimbeg/algorithmic-efficiency/algorithmic_efficiency/checkpoint_utils.py", line 92, in maybe_restore_checkpoint
model_params.load_state_dict(checkpoint_state['model_params'])
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1605, in load_state_dict
    model_params.load_state_dict(checkpoint_state['model_params'])
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1605, in load_state_dict
    model_params.load_state_dict(checkpoint_state['model_params'])
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1605, in load_state_dict
        self.__class__.__name__, "\n\t".join(error_msgs)))        self.__class__.__name__, "\n\t".join(error_msgs)))
self.__class__.__name__, "\n\t".join(error_msgs)))    RuntimeErrorself.__class__.__name__, "\n\t".join(error_msgs)))

self.__class__.__name__, "\n\t".join(error_msgs))):
self.__class__.__name__, "\n\t".join(error_msgs)))RuntimeErrorself.__class__.__name__, "\n\t".join(error_msgs)))self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeErrorError(s) in loading state_dict for DistributedDataParallel:
        Missing key(s) in state_dict: "module.conv1.weight", "module.bn1.weight", "module.bn1.bias", "module.bn1.running_mean", "module.bn1.running_var", "module.layer1.0.conv1.we
ight", "module.layer1.0.bn1.weight", "module.layer1.0.bn1.bias", "module.layer1.0.bn1.running_mean", "module.layer1.0.bn1.running_var", "module.layer1.0.conv2.weight", "module.lay
er1.0.bn2.weight", "module.layer1.0.bn2.bias", 

## Steps to Reproduce
Current commit:
```
commit 92ec3d69d29006c3cac2db5571ce1ea299df183a (HEAD -> main, origin/main, origin/HEAD, kasimbeg/main)
Merge: 5d0e9fd 21e47e0
Author: Zachary Nado <znado@users.noreply.github.com>
Date:   Thu Oct 20 11:18:09 2022 -0400

    Merge pull request #209 from runame/fix-fastmri-ddp
    
    Fix wrong eval metrics for FastMRI with PyTorch DDP
```

On kasimbeg-4 ran command:
```
orchrun --redirects 1:0,2:0,3:0,4:0,5:0,6:0,7:0 --standalone --nnodes=1 --nproc_per_node=8 submission_runner.py     --framework=pytorch     --data_dir=~/local_data/imagenet/pytorch     --imagenet_v2_data_dir=~     --experiment_dir=~     --experiment_name=target_setting     --workload=imagenet_resnet     --submission_path=reference_algorithms/target_setting_algorithms/pytorch_nesterov.py     --tuning_search_space=reference_algorithms/target_setting_algorithms/imagenet_resnet/tuning_search_space.json     --profile
```

## Source or Possible Fix
It ran ok on wednesday morning, let's say this commit not broken. 
```
commit 25d892bdc10caa5241c9afec38eeb116e814c70c
Merge: 26f9f80 70c4140
Author: Zachary Nado <znado@users.noreply.github.com>
Date:   Tue Oct 18 20:39:12 2022 -0400

    Merge pull request #200 from mlcommons/priyakasimbeg-patch-1
    
    Update README.md for target_setting
```

Check diff between this and current state.

**Comment by priyakasimbeg** [comment]
I'm not sure why it's trying to load the model state dict. Is there a flag that we now have to specify a new experiment?

**Comment by pomonam** [comment]
This is probably due to PR #181 and I suspect the reason is that the model architecture changed between the point you initially ran the code and the point you are running. 

To fix this, you can remove the corresponding checkpoint at `experiment_dir`. Once you delete `checkpoint`, it will no longer try to load the `state_dict`.

**Comment by priyakasimbeg** [comment]
Ok turns out I had a couple experiment directories I had to remove. 
Open question: I don't really like that it tries to resume an experiment by default. Is that the desired behavior @znado?

**Comment by pomonam** [comment]
Ideally, you can specify `--experiment_name` in the flag (e.g., `--experiment_name trial1`) which avoids resuming the experiment with a different name, but we can discuss the behaviour.

**Comment by priyakasimbeg** [comment]
I think it would be more desirable to have it automatically start a new trial: It by default sets up <experiment_dir>/imagenet_resnet_pytorch/trial_1. If we run it again it should set up <experiment_dir>/iamgenet_resnet_pytorch/trial_2. 
I think resuming a trial can be specified explicitly with maybe a `--resume_from_trial` flag. If the flag is set and the trial exists in the experiment (sub)directory it will resume that trial.

What do you think?

**Comment by znado** [comment]
I think it makes sense to have a `Confirm you want to resume [y/N]` prompt that if you just hit enter it will not resume.

**Comment by pomonam** [comment]
I am happy with both having `--resume_from_trial`or a prompt confirming to resume. If @priyakasimbeg also thinks that the prompt is useful, I can do the implementation.

**Comment by priyakasimbeg** [comment]
Thanks Juhan! 
So to make sure we are on the same page; we are not going with my initial suggestion and instead resuming the trial as a default but adding the prompt `Confirm you want to resume [y/N]` 
I think it would also be necessary in case the user says `N` to set up the next trial 
 automatically (e.g `<experiment_dir>/<experiment_name>/imagenet_resnet_pytorch/trial_2)`. I'm not sure if the functionality to set up a new trial manually exists since the user only has `experiment_dir` and `experiment_name` flags. Does that agree with your understanding of the current state?

**Comment by priyakasimbeg** [comment]
Actually, I misunderstood what the trial run directories were for. I just realized that the trial directories are for the tuning runs, so disregard the automatic directory set up. I think we just want the prompt for now.
