### ISSUE TITLE
Document development flow for making a submission

### ISSUE THREAD

**Issue by znado** [mlcommons/algorithmic-efficiency#277]
We need to write a detailed .md file that describes:

1. how `submission_runner.py` runs the algorithm and workload
2. how the different submission functions are expected to behave (pmap for jax, device placement for pytorch, data selection, etc)
3. piecing together a simple example submission

This file should probably be something like `getting_started.md` or `submission_development.md` or something descriptive, in the root dir of the repo, and linked to from the README.

**Comment by priyakasimbeg** [comment]
Fixed in https://github.com/mlcommons/algorithmic-efficiency/pull/427
