### ISSUE TITLE
Finish Dockerfile

### ISSUE THREAD

**Issue by znado** [mlcommons/algorithmic-efficiency#278]
We need a working Dockerfile that has all the proper OS, GPU, and Python setup, that can easily work with our GCP project.

The last I looked at it, it was unclear:
- what the base image should be
- the best way to run GCP VMs using it

**Comment by sourabh2k15** [comment]
this seems to be the best base image for our purposes as it has cuda 11.7 cudnn 8.5 and ubuntu 20.04 that we already use on our existing VMs 

https://gitlab.com/nvidia/container-images/cuda/-/blob/master/dist/11.7.0/ubuntu2004/runtime/cudnn8/Dockerfile

**Comment by sourabh2k15** [comment]
docker command to pull above image : docker pull nvidia/cuda:11.7.0-cudnn8-runtime-ubuntu20.04
