### ISSUE TITLE
Add Adam baseline

### ISSUE THREAD

**Issue by bilal2vec** [mlcommons/algorithmic-efficiency#287]
## Adam Baseline

- Implementation: Optax's AdamW
- Tunable hyperparameters: `learning_rate, b1, b2, weight_decay` 
- Fixed hyperparameters: `epsilon=1e8, eps_root=0.0`

**Comment by runame** [comment]
I assume the LR schedule is the same as for the target-setting runs?

Should `label_smoothing`, `grad_clip`, and `warmup_steps` be tunable hyperparameters? And what about the same hyperparamters for the other baselines (for the ones with polynomial LR schedule also `end_factor` and `decay_steps_factor`)?

**Comment by runame** [comment]
Addressed by #306.
