### ISSUE TITLE
WMT Workload for Translation: PyTorch

### ISSUE THREAD

**Issue by fsschneider** [mlcommons/algorithmic-efficiency#29]
### Workload

**Task**

Translation

**Dataset**

WMT'17 en <-> de

**Model**

Transformer

**Reference Implementation**

[Our JAX implementation](https://github.com/mlcommons/algorithmic-efficiency/tree/main/workloads/wmt/wmt_jax) can be used as a direct reference.

There is also an existing[ MLCommons Training implementation](https://github.com/mlcommons/training/tree/master/translation) for TensorFlow.

**Comment by fsschneider** [comment]
Rajath is looking into porting the JAX implementation to PyTorch. Once I figure out how to assign people, I will do this for this workload :)

**Comment by Rajathbharadwaj** [comment]
Yes, I will look into it.

**Comment by runame** [comment]
Added in PR #66.
