### ISSUE TITLE
Add Adafactor Baseline

### ISSUE THREAD

**Issue by bilal2vec** [mlcommons/algorithmic-efficiency#293]
## Adafactor

- Implementation: Internal fork of https://github.com/google/praxis/blob/main/praxis/optimizers.py, can open-source
- Fixed hyperparameters:
```
      'opt_hparams': {
          'layerwise_adaptation': False,
          'decay_method': 'adam',
          'decay_adam': 0.99,
          'decay_pow': 0.0,
          'beta1': 0.9,
          'clip_threshold': 1.0,
          'factored': True,
          'epsilon1_grad_sq_reg': 1e-30,
          'respect_skip_lp_regularization': False,
          'exclude_from_layerwise_adaptation': None,
          'per_var_learning_summary': False,
          'sort_factored_second_moment_dims': False,
          'min_dim_size_to_factor': 128,
          'multiply_by_parameter_scale': False,
          'epsilon2_param_scale_reg': 1e-3,
          'maybe_inf_to_nan': True,
      },
```
- Tuned hyperparameters: `learning_rate, beta1, decay_adam, weight_decay`

**Comment by znado** [comment]
`decay_pow` can be [ignored](https://github.com/google/praxis/blob/main/praxis/optimizers.py#L2194) because we set `'decay_method': 'adam'`

**Comment by znado** [comment]
Note that our internal fork should be equivalent to [`sharded_adafactor`](https://github.com/google/praxis/blob/main/praxis/optimizers.py#L2341).

**Comment by runame** [comment]
Addressed by #313 and #347.

**Comment by runame** [comment]
@bilal2vec `beta1` is listed as a fixed AND tuned hparam, which one is correct?

**Comment by runame** [comment]
cool, thanks for the quick reply!
