### ISSUE TITLE
Add Sharpness Aware Minimization Baseline

### ISSUE THREAD

**Issue by bilal2vec** [mlcommons/algorithmic-efficiency#301]
## Sharpness Aware Minimization (SAM)

- Implementation: A modified internal version of the open-source official version from (https://github.com/google-research/sam) applied on top of Adam, can open source.
- Tunable hyperparameters: Trust region parameter $\rho$, tunes the same hyperparams as the Adam baseline.
- Fixed hyperparameters/design decisons: Doesn't use M-sharpness, same fixed hyperparams as the Adam baseline

**Comment by runame** [comment]
Can you open source the modified internal version or share it with me somehow?

**Comment by runame** [comment]
Added in #325 and #347.
