### ISSUE TITLE
LibriSpeech RNN-T Workload for ASR: JAX

### ISSUE THREAD

**Issue by fsschneider** [mlcommons/algorithmic-efficiency#31]
### Workload

**Task**

Automatic Speech Recognition

**Dataset**

LibriSpeech (clean 100 hour)

**Model**

Deep Speech model (CNN LSTM)

**Reference Implementation**

Leda provided us with a [reference implementation in PyTorch](https://github.com/lsari/librispeech_100/blob/main/models.py).

A PyTorch implementation is currently in progress, see the PR #27 and the associated issue #30.

There is also an existing[ MLCommons Training implementation](https://github.com/mlcommons/training/tree/master/rnn_speech_recognition/pytorch) for PyTorch.

**Comment by kamalkraj** [comment]
Hi @fsschneider,
I would like to work on JAX implementation.

**Comment by fsschneider** [comment]
Wonderful!

@znado do you two want to meet to discuss tackling this workload?

@kamalkraj Let me know if there is anything you need that I can help you with. I linked our current PR for the PyTorch version. It is in a working state and we are currently checking whether we can boost the performance of our trained model further. But this should be a good reference implementation.

**Comment by sourabh2k15** [comment]
Now that we have deepspeech jax workload working, we can close this issue
