### ISSUE TITLE
PyTorch conformer model broken for PyTorch 1.13.x

### ISSUE THREAD

**Issue by runame** [mlcommons/algorithmic-efficiency#317]
The PyTorch conformer model throws the following error ([here](https://github.com/mlcommons/algorithmic-efficiency/blob/main/algorithmic_efficiency/workloads/librispeech_conformer/librispeech_pytorch/models.py#L390-L402)) when PyTorch 1.13.0 is used (which is the version in our requirements):
```
return torch._native_multi_head_attention(
RuntimeError: Mask Type should be defined
```

**Comment by sourabh2k15** [comment]
this is now fixed by https://github.com/mlcommons/algorithmic-efficiency/pull/321
