### ISSUE TITLE
DLRM Workload for Recommendation: PyTorch

### ISSUE THREAD

**Issue by fsschneider** [mlcommons/algorithmic-efficiency#32]
### Workload

**Task**

Binary Classification

**Dataset**

Criteo Terabyte dataset

**Model**

DLRM

**Reference Implementation**

There is an existing[ MLCommons Training implementation](https://github.com/mlcommons/training/tree/master/recommendation) for PyTorch.

**Comment by fsschneider** [comment]
For some reason, I couldn't assign or tag Rakshith or Nikola. Just wanted to note down that [they are currently working on this](https://github.com/rakshithvasudev/algorithmic-efficiency/tree/main/workloads/dlrm).

**Comment by pomonam** [comment]
The PR @146 (https://github.com/mlcommons/algorithmic-efficiency/pull/146) implements this workload.
