### ISSUE TITLE
DLRM Workload for Recommendation: JAX

### ISSUE THREAD

**Issue by fsschneider** [mlcommons/algorithmic-efficiency#33]
### Workload

**Task**

Binary Classification

**Dataset**

Criteo Terabyte dataset

**Model**

DLRM

**Reference Implementation**

A PyTorch implementation is currently in progress, see [here](https://github.com/rakshithvasudev/algorithmic-efficiency/tree/main/workloads/dlrm) and the associated issue #32 

There is an existing[ MLCommons Training implementation](https://github.com/mlcommons/training/tree/master/recommendation) for PyTorch.

**Comment by pomonam** [comment]
This PR https://github.com/mlcommons/algorithmic-efficiency/pull/136 implements the workload.
