### ISSUE TITLE
fastMRI Workload for Regression: PyTorch

### ISSUE THREAD

**Issue by fsschneider** [mlcommons/algorithmic-efficiency#37]
### Workload

**Task**

Regression
MRI reconstruction from subsampled, raw scanner data

**Dataset**

[fastMRI](https://fastmri.med.nyu.edu/)

**Model**

U-Net (like things)

**Reference Implementation**

Existing implementations: [Facebook (PyTorch) implementation](https://github.com/facebookresearch/fastMRI/) with a model from [this paper](https://arxiv.org/abs/2004.06688)

**Other Info**

[Website](fastmri.org/dataset)
NeurIPS competition: [2019 (knee)](https://arxiv.org/abs/2001.02518), [2020 (brain)](https://arxiv.org/abs/2012.06318)

**Comment by fsschneider** [comment]
I am currently double-checking the licensing for the fastMRI dataset.

They already gave us positive feedback, so this workload is ready to implement. This is just a note to myself.

**Comment by runame** [comment]
Added in PR #86.
