### ISSUE TITLE
Add option to save checkpoint with lowest validation score only

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#377]
My VMs are running out of memory for timing runs because the checkpoints of all evals are saved by default. 
This will be an issue for scoring too.

**Comment by runame** [comment]
@priyakasimbeg Can this issue be closed?

**Comment by priyakasimbeg** [comment]
Added an option to save just last eval checkpoint, which I think is good enough for now to deal with the memory issue. 
If people would rather save the checkpoint with the lowest eval, we'll open a new issue.
