### ISSUE TITLE
Timing bug for Pytorch momentum and nesterov resnet and conformer

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#394]
## Description
Pytorch momentum and nesterov algorithms submission times don't add up: the update and eval times do not add up to the total submisison time. The result is that the meausred submission times for momentum on resnet and momentum and nesterov on conformer are 20% and 50% faster than the other algorithms.

## Steps to Reproduce

On branch [timing_test_2](https://github.com/priyakasimbeg/algorithmic-efficiency/tree/timing_test_2) (diffs w main are summarized below) run:
```
torchrun --redirects 1:0,2:0,3:0,4:0,5:0,6:0,7:0 --standalone --nnodes=1 --nproc_per_node=8 submission_runner.py --framework=pytorch --workload=imagenet_resnet --submission_path=baselines/momentum/pytorch/submission.py --tuning_search_space=baselines/momentum/tuning_search_space.json --data_dir=/data/imagenet/pytorch --num_tuning_trials=1 --experiment_dir=/experiment_runs --experiment_name=debug_momentum_timing  --overwrite=True --save_checkpoints=False --max_global_steps=28000 --imagenet_v2_data_dir=/data/imagenet/pytorch 2>&1 | tee -a imagenet_resnet_pytorch_timing.log
```

Note you'll probably want to modify the paths for the data_dir and imagenet_v2_data_dir depending on where your data is stored.

Also for convenience the command for conformer momentum:
```
torchrun --redirects 1:0,2:0,3:0,4:0,5:0,6:0,7:0 --standalone --nnodes=1 --nproc_per_node=8 submission_runner.py --framework=pytorch --workload=librispeech_conformer --submission_path=baselines/momentum/pytorch/submission.py --tuning_search_space=baselines/momentum/tuning_search_space.json --data_dir=/data/librispeech --num_tuning_trials=1 --experiment_dir=/experiment_runs --experiment_name=timing_v3_b_pytorch/timing_momentum --overwrite=True --save_checkpoints=False --max_global_steps=20000 --librispeech_tokenizer_vocab_path=/data/librispeech/spm_model.vocab 2>&1 | tee -a librispeech_conformer_pytorch.log
```

The main diffs between the timing_test_2 branch and main branch are:
- I moved the pytorch sync for train_step_start time to  before the prng fold_in step consistent w the jax timing. 
- Include data_selection time for debugging

## Source or Possible Fix

The issue is most likely a bug related to how we time the pytorch DDP update because the eval times and submission times don't add up to the total time.

**Comment by pomonam** [comment]
@runame Maybe this is the [link](https://discuss.pytorch.org/t/how-to-measure-time-in-pytorch/26964) you are talking about?

**Comment by runame** [comment]
Yeah, the keyword is `torch.cuda.synchronize()`, I don't think this is used anywhere in the timing code. See the brief note [here](https://discuss.pytorch.org/t/how-to-measure-execution-time-in-pytorch/111458). Maybe this is already the bug, but there is also more sophisticated stuff, see e.g. [here](https://www.speechmatics.com/company/articles-and-news/timing-operations-in-pytorch) -- I haven't looked into this though.
