### ISSUE TITLE
Resuming from checkpoint fails when using TORCH_DDP

### ISSUE THREAD

**Issue by RossM** [mlcommons/algorithmic-efficiency#412]
## Description

Resuming from a checkpoint using --resume_last_run when using multiple threads with `torchrun` has two issues:

First, the `DistributedDataParallel` is not unwrapped, so loading the model parameters fails, meaning you effectively start from a newly initialized model.

Second, if that is fixed, training hangs immediately after the start of the training loop.

## Steps to Reproduce

`torchrun --nnodes=1 --nproc_per_node=8 submission_runner.py --framework=pytorch --resume_last_run ...`

## Source or Possible Fix

For the first problem, in `algorithmic_efficiency/checkpoint_utils.py`, replace both instances of `if isinstance(model_params, torch.nn.DataParallel)` with `hasattr(model_params, 'module')` to correctly unwrap DistributedDataParallel.

For the second problem, `get_log_dir()` in `algorithmic_efficiency/logger_utils.py` returns None for all processes except rank 0, so rank 0 loads the checkpoint and the remaining processes don't, which causes the processes to have inconsistent states and hang during an all_wait. I have a local band-aid fix but this needs attention from someone who understands the existing code.

**Comment by pomonam** [comment]
Thank you for submitting the issue and adding detailed instructions for fixing the issue! I started a draft #438; feel free to comment on it :)

**Comment by Niccolo-Ajroldi** [comment]
Any update on this? 

@RossM can you share your fix in the meanwhile? Thanks!

**Comment by priyakasimbeg** [comment]
@pomonam can we pick this up again?

**Comment by pomonam** [comment]
Sorry for the delay - this should be fixed in #755.
