### ISSUE TITLE
Dockerfile for torch 

### ISSUE THREAD

**Issue by sourabh2k15** [mlcommons/algorithmic-efficiency#415]
## Description

While testing https://github.com/mlcommons/algorithmic-efficiency/pull/393 we found that installing both jax and torch GPU versions breaks the deepspeech code since torch GPU install comes with it's own version of cudnn which doesn't match the the minimum version we need for jax (cudnn >= 8.6) 

We either need 2 seperate docker files or a branch in existing Dockerfile to get CPU version of the other framework installed along with GPU version of the framework being run 

Currently we have JAX GPU and torch CPU in our Dockefile, this needs to be fixed in one of ways described above

**Comment by sourabh2k15** [comment]
@runame @priyakasimbeg

**Comment by priyakasimbeg** [comment]
Per discussion w Zack we will add an arg to the existing dockerfile to specify the framework https://github.com/mlcommons/algorithmic-efficiency/pull/417
