### ISSUE TITLE
Add instructions on how to run docker image with singularity/apptainer

### ISSUE THREAD

**Issue by runame** [mlcommons/algorithmic-efficiency#436]
## Description

Since many HPCs don't grant root access and have singularity/[apptainer](https://github.com/apptainer/apptainer) pre-installed, it might be helpful to add instructions on how to use the docker image with singularity/apptainer.

**Comment by priyakasimbeg** [comment]
From email thread; @runame suggests converting Docker images to singularity/apptainer as described in this [guide](https://portal.mlcloud.uni-tuebingen.de/user-guide/containers/)

**Comment by priyakasimbeg** [comment]
Fixed in https://github.com/mlcommons/algorithmic-efficiency/pull/516
