### ISSUE TITLE
Cannot download criteo dataset with dataset downloader

### ISSUE THREAD

**Issue by ezyang** [mlcommons/algorithmic-efficiency#469]
This is not a hard blocker since you can get it from https://ailab.criteo.com/download-criteo-1tb-click-logs-dataset/ but the downloader script seems to be pointed at https://sacriteopcail01.z16.web.core.windows.net/ which appears to be down right now

**Comment by znado** [comment]
Unfortunately Criteo changed their data hosting solution again, you can use https://github.com/iamleot/transferwee to download it to a headless host. We are working on integrating that into our download script so you don't have to do an extra step, PR coming shortly!

**Comment by priyakasimbeg** [comment]
Bumping priority on this since this and https://github.com/mlcommons/algorithmic-efficiency/issues/479 Criteo Preprocessing are blocking debugging of Criteo issues. 
@runame will look into this

**Comment by priyakasimbeg** [comment]
Should be fixed in https://github.com/mlcommons/algorithmic-efficiency/pull/499
Thanks @runame and @znado!
