### ISSUE TITLE
criteo preproc doesn't match input_pipeline

### ISSUE THREAD

**Issue by ezyang** [mlcommons/algorithmic-efficiency#479]
input_pipeline.py hardcodes 36 day 23 files, but the preproc script splits into 1000000 chunks resulting in 100+ files. I think the expected split size was 5000000 which gets you about 36 splits.

**Comment by priyakasimbeg** [comment]
@runame this may be relevant too for fixing the datasetup, I think @ezyang 
is referring to this line: https://github.com/mlcommons/algorithmic-efficiency/blob/main/datasets/dataset_setup.py#L279. 
We should probably after fixes check that the files match what is stored on our GCP data bucket and your set up VM with checksum or sth.
