### ISSUE TITLE
dataset_setup still needs TF

### ISSUE THREAD

**Issue by msaroufim** [mlcommons/algorithmic-efficiency#482]
Not a huge deal but you can see a call here https://github.com/mlcommons/algorithmic-efficiency/blob/main/datasets/dataset_setup.py#L563

I feel like it'd be very helpful to run dataset preparation in CI once a night to catch this stuff

**Comment by priyakasimbeg** [comment]
Thanks for catching this! Added it back in https://github.com/mlcommons/algorithmic-efficiency/pull/485

**Comment by priyakasimbeg** [comment]
And yes you're right we are lacking data setup tests at the moment. 
There are a few challenges for these tests:
-  datasets are very large (total just under 2TB total I believe) 
-  some of them require manual steps (getting the links after signing the user agreements etc, I don't think we can check in the urls). 

We can at a minimum test the datasets that are downloaded via tfds (ogbg and wmt) and add some unit tests for the other datasets. I'll open a new issue to track this.

**Comment by priyakasimbeg** [comment]
Fixed in https://github.com/mlcommons/algorithmic-efficiency/pull/485
