### ISSUE TITLE
OGBG timing gap and torch compile bug

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#495]
OGBG pytorch is slower in jax by ~11% and has torch compilation issues.

## Description
Torch compile is blocked on this workload by Dynamo tracing bug of NamedTuple.
See https://github.com/pytorch/pytorch/issues/107040.

## Steps to Reproduce
See See https://github.com/pytorch/pytorch/issues/107040.

## Source or Possible Fix
We could try to factor out the NamedTuple out of our implementation as a medium term solution while the Dynamo tracing bug is being fixed.

**Comment by msaroufim** [comment]
Hi @priyakasimbeg could I get permissions to create labels? Wanna mark this as a pytorch one and other issues

**Comment by priyakasimbeg** [comment]
@msaroufim could you request to join https://github.com/orgs/mlcommons/teams/special-algorithms?

**Comment by msaroufim** [comment]
I know this is 3 weeks late xd but that link just gives me a 404

**Comment by priyakasimbeg** [comment]
Current status is that ogbg is 6% slower w pytorch. I'm going to close this for now.
