### ISSUE TITLE
Handling of the TrainingCompleteError

### ISSUE THREAD

**Issue by fsschneider** [mlcommons/algorithmic-efficiency#5]
Currently, the `spec.TrainingCompleteError` allows unlimited untimed evaluations.

**Steps to reproduce:**
Compare running the example submission via
```bash
python3 submission_runner.py --workload=mnist_jax --submission_path=workloads/mnist_jax/submission.py --num_tuning_trials=1
```
versus a slightly modified version of the submission. This modified version simply raises the `TrainingCompleteError` in the first step, e.g. by replacing 
https://github.com/mlcommons/algorithmic-efficiency/blob/effe55a0e97c82500861e34f52f7894534be79e3/workloads/mnist_jax/submission.py#L56
with
```python
if global_step == 0:
  raise spec.TrainingCompleteError
```
While the example submission evaluates three times until the goal is reached in step 40 (and roughly 20 secs)
![image](https://user-images.githubusercontent.com/12153723/115740534-3339aa00-a38f-11eb-9a20-0bb7a09e8b4f.png)

the modified version is evaluated in each step and reaches it already in step 34 (and roughly 17 secs)
![image](https://user-images.githubusercontent.com/12153723/115740639-519fa580-a38f-11eb-9d05-0bcb1b251b7d.png)

**Source**
Once the `TrainingCompleteError` has been raised `eval_now` will be set to `True` which will never change.
https://github.com/mlcommons/algorithmic-efficiency/blob/effe55a0e97c82500861e34f52f7894534be79e3/submission_runner.py#L119-L120
An untimed eval is done whenever `eval_now==True`:
https://github.com/mlcommons/algorithmic-efficiency/blob/effe55a0e97c82500861e34f52f7894534be79e3/submission_runner.py#L126-L133

**Possible Fix**
I believe, once the submission raises the `TrainingCompleteError` training should completely stop after the evaluation. Therefore, adding a check whether `eval_now` has been set to `True` could be added to the overall training loop which should fix the problem
https://github.com/mlcommons/algorithmic-efficiency/blob/effe55a0e97c82500861e34f52f7894534be79e3/submission_runner.py#L87

**Comment by hanlint** [comment]
I just saw this -- ran into the issue independently, and adopted a similar solution: 

https://github.com/mlcommons/algorithmic-efficiency/pull/7/files#diff-896efaf84526ad88de1d33384cae90f5df290c08de07ec039209e6d4c7bc27c7L87

**Comment by fsschneider** [comment]
@hanlint @znado I believe that this issue can be closed, right?

**Comment by fsschneider** [comment]
I am closing this issue as I believe this is resolved.

I tested the example mentioned above again and in this test case, there is indeed only a single evaluation before training terminates via the `TrainingCompleteError`.
