### ISSUE TITLE
Set `DEVICE` globally and decide where to transfer batches to the chosen device

### ISSUE THREAD

**Issue by runame** [mlcommons/algorithmic-efficiency#50]
Currently, for the PyTorch workloads the `DEVICE` is just hard-coded/set based on availability in each workload, e.g. [here](https://github.com/mlcommons/algorithmic-efficiency/blob/main/workloads/mnist/mnist_pytorch/workload.py#L17). The `DEVICE` should probably be set globally for all workloads to avoid inconsistencies. Maybe the user should even have the option to choose the device or the number of GPUs to use (in the GPU case), at least in "debug mode".

Moreover, in the PyTorch workloads the training and evaluation batches are transferred to `DEVICE` in the `preprocess_for_{train|eval}()` function. We could get rid of these functions (and the need for the user to call them) in multiple ways. The simplest option is to just call `input_batch.to(DEVICE)` in `workload.model_fn()`. In this way, the batches are always on the appropriate device for each forward pass during training and evaluation.

**Comment by znado** [comment]
I agree, I think we were overly optimistic when we originally drafted the APIs, and based on how people are writing the input pipelines, `preprocess_for_{train|eval}` are unnecessary.

**Comment by runame** [comment]
Not really an issue anymore.
