### ISSUE TITLE
Pytorch workloads OOM after profiler update

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#518]
Pytorch workloads are OOMing on start after a recent update to our profiler.py.

## Description
The following pytorch workloads OOM on start on our dev branch:
- resnet
- vit
- conformer
- deepspeech
- criteo

For tracebacks, expand the"Run containerized workload" tab for the affected pytorch workloads in this [regression test](https://github.com/mlcommons/algorithmic-efficiency/actions/runs/6226044164/job/16943786819). 

I traced this new behavior to a change in our profiler.py by undoing the profiler changes and running the workloads again. Without the profiler changes the above workloads (with the exception of conformer know issue) run fine.

## Steps to Reproduce
To reproduce OOM checkout `dev` branch.
To reproduce lack of OOM checkout `dev_oom_debugging` branch (with profiler changes undone). 

Then run one of the workloads, e.g. resnet:
```
torchrun --redirects 1:0,2:0,3:0,4:0,5:0,6:0,7:0 --standalone --nnodes=1 --nproc_per_node=8 submission_runner.py --framework=pytorch --workload=imagenet_resnet --submission_path=baselines/adamw/pytorch/submission.py --tuning_search_space=baselines/adamw/tuning_search_space.json --data_dir=/data/imagenet/pytorch --num_tuning_trials=1 --experiment_dir=/experiment_runs --experiment_name=tests/regression_tests/adamw --overwrite=True --save_checkpoints=False --max_global_steps=10 --imagenet_v2_data_dir=/data/imagenet/pytorch --torch_compile=true 2>&1 | tee -a /logs/imagenet_resnet_pytorch_oom_debug.log
```

## Requirements for Fix
As far as I understand the profiler changes were necessary fixes for our pytorch multidevice setting. We should investigate further why we're running out of memory with these changes.

**Comment by runame** [comment]
For reference, [this](https://github.com/mlcommons/algorithmic-efficiency/pull/489/commits/426a5b8c4f43db104ef3035b93a2ff9675819789) is the change to the profiler that (surprisingly) seems responsible for the OOM errors. The change is also relevant for the single device setting.

**Comment by msaroufim** [comment]
When you make the first call to `.cuda` in a subprocess it will create a CUDA context which last I checked was around 500MB which might explain the OOM. Presumably you're only seeing the OOM on 1/8 of the devices?

**Comment by priyakasimbeg** [comment]
Fixed in https://github.com/mlcommons/algorithmic-efficiency/pull/519 , thanks for the suggestions @msaroufim!
