### ISSUE TITLE
Implement sampling function for hyperparameters and held-out workloads

### ISSUE THREAD

**Issue by fsschneider** [mlcommons/algorithmic-efficiency#540]
## Description

We need two functions:

- One that, given a seed provided by a "trusted third party" samples the held-out workloads (one for each dataset) to use in the competition.
- One function that, given a seed and a submission ID, provides hyperparameter seeds, grouped by study, I.e. 5 groups of 5 hyperparameter configurations.

**Comment by priyakasimbeg** [comment]
@fsschneider I'm not sure if I understand the second sampling function. Please correct me if this is wrong, assuming the hyperparameter configurations correspond to tuning trials (which should be 5 trials now), what do the studies correspond to?

**Comment by priyakasimbeg** [comment]
From offline thread it looks like we want to sample 6 total and score with option 2.
