### ISSUE TITLE
Scoring code needs to account for held-out workload performance

### ISSUE THREAD

**Issue by fsschneider** [mlcommons/algorithmic-efficiency#588]
The benchmark rules describe that submissions also need to perform well on held-out workloads. This is currently not automatically accounted for in the scoring code.
Specifically, (quoting from the [benchmark rules](https://github.com/mlcommons/algorithmic-efficiency/blob/main/RULES.md#using-held-out-workloads-in-scoring)):
For a submission to receive a finite training time on a fixed workload, it needs to:

- Reach the validation target on the fixed workload within the maximum runtime.
- Reach the validation target fixed workload within 4x of the fastest submission.
- Reach the validation target on the held-out workload (corresponding to the fixed workload) within the maximum runtime.
- Reach the validation target on the held-out workload (corresponding to the fixed workload) within 4x of the fastest submission. To determine the fastest submission on a held-out workload, we only consider submissions that reached the target on the corresponding fixed workload. This protects us against extremely fast submissions that only work on a specific held-out workload and are useless as general algorithms.

**Comment by priyakasimbeg** [comment]
Remaining work on this is to add tests that check if all 4 criteria are enforced in strict mode.

**Comment by priyakasimbeg** [comment]
Moved tracking of tests to https://github.com/mlcommons/algorithmic-efficiency/issues/624
