### ISSUE TITLE
Include modeldiff tests in github workflows

### ISSUE THREAD

**Issue by runame** [mlcommons/algorithmic-efficiency#601]
## Description

We currently just print the result of the modeldiff tests. I think it would make sense to decide on thresholds for all workloads, such that we can make a binary pass/fail decision for each test. Then we should include the tests in our github workflows. This would guarantee that any future model changes won't lead to inconsistencies between Jax and PyTorch without the devs having to manually run anything.

**Comment by priyakasimbeg** [comment]
@runame do you have time to add these tests to our CI configs?

**Comment by runame** [comment]
Yes, I can work on this next week.
