### ISSUE TITLE
num_workers=0 in ImageNet DataLoader

### ISSUE THREAD

**Issue by Niccolo-Ajroldi** [mlcommons/algorithmic-efficiency#638]
This is more of a question than an issue.

The **number of workers** for torch `DataLoader` is set to zero for ImageNet during evaluation (on `train`, `valid` and `test` splits). However, this makes evaluation extremely slow in my setting.

Maybe I am missing something, hence I would like to ask:
- Why is the number of workers set to zero during evaluation?
- Are we allowed to change the number of workers for evaluation to be 4 when self-reporting results? 
Under the rules, model evaluations should be untimed and not contribute to the submissions score, so this shouldn't influence the final score. Is this correct?

Here is the relevant code:
https://github.com/mlcommons/algorithmic-efficiency/blob/11b11ec8160b0ca5b1503d85125420247fc58d16/algorithmic_efficiency/workloads/imagenet_resnet/imagenet_pytorch/workload.py#L129

Notice that for other datasets like _librispeech_, the number of workers is always 4:
https://github.com/mlcommons/algorithmic-efficiency/blob/11b11ec8160b0ca5b1503d85125420247fc58d16/algorithmic_efficiency/workloads/librispeech_conformer/librispeech_pytorch/workload.py#L176

Why this discrepancy?

Thanks in advance!

**Comment by priyakasimbeg** [comment]
@pomonam do you have any context around this?

**Comment by pomonam** [comment]
Sorry for the late reply! Yes, changing `num_workers` should not affect the final results because the evaluation time is not measured. Please feel free to change these numbers when running your experiments.

**Comment by priyakasimbeg** [comment]
@runame added a flag to control the num_workers for some datasets during eval. 
Hope that helps!

**Comment by Niccolo-Ajroldi** [comment]
Thank you, @runame!
