### ISSUE TITLE
Mismatch between Maximum Runtime in the DOCS and `max_allowed_runtime_sec` in the code

### ISSUE THREAD

**Issue by Niccolo-Ajroldi** [mlcommons/algorithmic-efficiency#660]
## Description

The "maximum runtime" of [this table](https://github.com/mlcommons/algorithmic-efficiency/blob/main/DOCUMENTATION.md#fixed-workloads) differ from `max_allowed_runtime_sec` in the code.

Few examples below:

Criteo:
https://github.com/mlcommons/algorithmic-efficiency/blob/a1bff1479fdbe7d8386c6a31bb75f42a19b0cacc/algorithmic_efficiency/workloads/criteo1tb/workload.py#L96

Deepspeech:
https://github.com/mlcommons/algorithmic-efficiency/blob/a1bff1479fdbe7d8386c6a31bb75f42a19b0cacc/algorithmic_efficiency/workloads/librispeech_deepspeech/librispeech_pytorch/workload.py#L84

ViT:
https://github.com/mlcommons/algorithmic-efficiency/blob/a1bff1479fdbe7d8386c6a31bb75f42a19b0cacc/algorithmic_efficiency/workloads/imagenet_vit/workload.py#L84

**Comment by priyakasimbeg** [comment]
Thanks for bringing this to our attention. The docs seem to be out of date. Will update them. 
In the meantime please refer to the code as the source of truth.
