### ISSUE TITLE
Training does not stop at target achievement

### ISSUE THREAD

**Issue by Niccolo-Ajroldi** [mlcommons/algorithmic-efficiency#678]
## Description

Training does not stop when both validation and test targets are reached, **resulting in a final score always equal to** `max_allowed_runtime`. The issue appears both in wandb logs and in standard out.

## Source or Possible Fix
By inspecting `submission_runner.py`, I spotted a bug in the code.
Simplifying, this is how `train_once` looks like now:
```
goals_reached = ..
  while not goals_reached:
    # train
```
However, `goals_reached` is not updated anymore after declaration! This is how this block look like:
```
goals_reached = ..
  while not goals_reached:
    # train
    goals_reached = ...
```

**Comment by priyakasimbeg** [comment]
Thanks for catching this and proposing a fix! I'll merge in a fix since the CLA process might take a few days.
