### ISSUE TITLE
Mismatch between target values in `workload.py` files and on `DOCUMENTATION.md` page

### ISSUE THREAD

**Issue by tfaod** [mlcommons/algorithmic-efficiency#684]
A few weeks ago, I noticed that the target values on the “getting started” are not consistent with the target values specified in the `workload.py` files. I thought this was a typo and previously I updated the `workload.py` files with the validation values. 

This week, I noticed that our training runs are hitting the target values specified in the workload.py but not the Getting Started documentation. For example, our fastmri workload consistently hits the test target, but never the val target from `DOCUMENTATION.md`. 

Could we confirm that the `workload.py` target files are correct, and fix this discrepancy? Thanks!!

**Comment by priyakasimbeg** [comment]
Hi, we are working on updating the documentation with the correct targets and maximum runtimes.
In the meantime please refer to the workload.py files as the source of truth.

@runame
