### ISSUE TITLE
Move common PyTorch/Jax specific functions to separate files

### ISSUE THREAD

**Issue by runame** [mlcommons/algorithmic-efficiency#74]
## Description

Move common Jax/PyTorch workload functions to separate class or `{jax/pytorch}_utils.py` file, see [this comment](https://github.com/mlcommons/algorithmic-efficiency/pull/66#discussion_r842320933).

**Comment by znado** [comment]
We can always keep cleaning the code up, but I think this is mostly resolved, gonna open a few more specific issues.
