### ISSUE TITLE
Update results date

### ISSUE THREAD

**Issue by josejg** [mlcommons/algorithmic-efficiency#773]
Based on the [CALL_FOR_SUBMISSIONS](https://github.com/mlcommons/algorithmic-efficiency/blob/main/CALL_FOR_SUBMISSIONS.md#dates), results were to be announced on July 15th. 

Is there an updated release date?

**Comment by priyakasimbeg** [comment]
Hi Jose,
We are in the final stages of evaluating submissions. We are doing some due diligence and rerunning training runs that failed due to hardware related issues (VM reboots etc). We expect that the results will be public by August 2nd.

**Comment by fsschneider** [comment]
We have now announced the results.
Please check out the [MLCommons blog post](https://mlcommons.org/2024/08/mlc-algoperf-benchmark-competition/) or our [results page](https://mlcommons.org/benchmarks/algorithms/).

@priyakasimbeg I create PR #782 to update the readme.

I think this closes this issue. Feel free to open it again if not.
