### ISSUE TITLE
Scoring logging bug 🐛 -  incorrect computation of `time to target on val (s)` in `get_summary_df`

### ISSUE THREAD

**Issue by Niccolo-Ajroldi** [mlcommons/algorithmic-efficiency#791]
## Description

In `scoring/score_submissions.py`, the function `get_summary_df` is responsible for gathering evaluation statistics from submission logs into a DataFrame. When scoring a submission, this function is invoked on every workload, and the resulting concatenated DataFrames are saved as CSV files (`<submission>_summary.csv` ).

The current implementation computes the time needed to reach the validation target as follows: 
https://github.com/mlcommons/algorithmic-efficiency/blob/a23b5ea298acdfae7366fb6ca175ab68f3a38f91/scoring/score_submissions.py#L91-L94

This results in a `time to target on val (s)` equal to `time to best eval on val (s)` if a submission reaches the target.  However, usually the time to the validation target is usually lower than the time to best eval score.

## Performance profiles are not affected
Fortunately, this bug **does not affect** the performance profiles, nor the final scores. Despite the concatenated DataFrames are used to compute the performance profiles, fortunately, we ignore the existing `time to target on val (s)` column and perform instead a correct computation of the time to eval target.

## Source or Possible Fix

I have implemented a fix in #792. The final scores and the performance profiles are unaffected after the fix. However, `<submission>_summary.csv` changes drastically. Here is an example on two workloads for the prize qualification baseline algorithm (first study):

![image](https://github.com/user-attachments/assets/f5074df6-0755-482b-9266-82b6714b2c9d)

**Comment by priyakasimbeg** [comment]
Thank you for identifying this issue and submitting a fix!
Confirming that this bug does not affect final scoring and performance profiles. The summary_df is only used for logging purposes and does not feed into the scoring pipeline. 
Just verified that in the scoring pipeline the time to target is computed correctly here: https://github.com/mlcommons/algorithmic-efficiency/blob/main/scoring/performance_profile.py#L155

**Comment by priyakasimbeg** [comment]
Fixed in https://github.com/mlcommons/algorithmic-efficiency/pull/792
