### ISSUE TITLE
data_selection function should take model_state as an argument

### ISSUE THREAD

**Issue by mikerabbat** [mlcommons/algorithmic-efficiency#8]
Currently the `data_selection` function takes `current_params` and `workload` as arguments, but it does not take `model_state`. For models that have batchnorm layers or other layers with state, it is not clear how this may be useful, e.g., if we want to enable submissions to have `data_selection` call `model_fn`. Should we also pass `model_state` here too?

https://github.com/mlcommons/algorithmic-efficiency/blob/e4406e574f4372a5025a9cc4e853d675fc4334de/spec.py#L272-L288

**Comment by znado** [comment]
Fixed in https://github.com/mlcommons/algorithmic-efficiency/pull/154
