### ISSUE TITLE
Fix torch import for users intending to use JAX framework

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#95]
The installation instructions are inconsistent with the pytorch import in submission_runner.py.

## Description
The submission_runner.py script imports torch whether or not the user intends to use the torch or JAX framework. The installation instructions say to install pytorch if using the torch framework. With the current instructions, users who are intending to use JAX and have not installed pytorch will get an import error. 

## Steps to Reproduce
Follow installation instructions for setting up a virtual environment for JAX framework.

## Source or Possible Fix
I think we should either:
1. if the torch dependency is necessary  for both jax and pytorch workflows, include torch in the default pip installation and remove instructions to install pytorch separately
2. if the torch dependency is only necessary for pytorch workflows, conditionally import torch

**Comment by runame** [comment]
See PR #115.
